<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\SharePointToAzureSearch.Core\SharePointToAzureSearch.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>SharePointToAzureSearch.aa86af98-b197-450b-8db6-45521bab965d</UserSecretsId>
  </PropertyGroup>

</Project>
